### ISSUE TITLE
You can use the vite as host to realize the official case "shared-directory"?

### ISSUE THREAD

**Issue by ghost** [TourmalineCore/vite-module-federation#1]
https://github.com/module-federation/module-federation-examples/tree/master/shared-directory

My use of vite as host is not working properly and cannot be shared

**Comment by akovylyaeva** [comment]
> https://github.com/module-federation/module-federation-examples/tree/master/shared-directory
> 
> My use of vite as host is not working properly and cannot be shared

Thank you for your question @kehuay !!
As we understand, you are making a wrapper over module federation to be able to connect applications on different bundlers and make a host application on vite. In our implementation, only the vite bundler is used, so yes, we are using vite application as host, but we connect it with another application on vite, not on a different bundler. 
We tried to connect vite with webpack and rsbuild, but as we understand, this cannot be done without additional wrappers. We also recommend to pay more attention to configs, a lot depends on them.
